import swaggerSpec from '../../../swagger-v1.json';

/**
 * Returns the raw OpenAPI 3.0 JSON specification.
 * Consumed by the Swagger UI handler and any external tooling (Postman, etc.).
 *
 * The spec is regenerated by running `npm run swagger` after adding
 * new endpoints.  The generated file (`swagger-v1.json`) is committed to
 * source control so deployments do not require a build step.
 */
export const handler = async () => ({
  statusCode: 200,
  headers: {'content-type': 'application/json'},
  body: JSON.stringify(swaggerSpec),
});
